name: Deploy Astro

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install deps
        run: npm ci

      - name: build
        run: npm run build

      - uses: actions/upload-pages-artifact@v1
        with:
          path: ./dist

      - uses: actions/deploy-pages@v1
        id: deployment

