name: Deploy Astro

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    name: Build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: bahmutov/npm-install@v1
        with:
          working-directory: ./
      - name: build
        run: npm run build
      - uses: actions/upload-pages-artifact@v1
        with:
          path: ./dist

